apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: broker
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: broker
    spec:
      containers:
      - name: broker
        image: eu.gcr.io/itonk-168412/broker:v1
        ports:
        - containerPort: 80
        env:
        - name: dbhost
          value: "35.187.53.157"
        - name: dbuser
          value: "doe"
        - name: dbpassword
          value: "1234"
        - name: dbdatabase
          value: "broker"
        - name: TaxApiAddress
          value: "http://taxtobin/"
        - name: RegistryApiAddress
          value: "http://registry/"
