apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: broker
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: broker
    spec:
      containers:
      - name: broker
        image: itonk/broker:v1
        ports:
        - containerPort: 80

