apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: provider
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: provider
    spec:
      containers:
      - name: provider
        image: itonk/provider:v1
        ports:
        - containerPort: 80
        env:
          - name: BrokerApiAddress
            value: "http://broker/"
          - name: "RegistryApiAddress"
            value: "http://registry/"

