apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: proxy
spec:
  replicas: 2
  template:
    metadata:
      labels:
        name: proxy
    spec:
      containers:
      - name: proxy
        image: eu.gcr.io/itonk-168412/proxy:v2
        ports:
        - containerPort: 80
