apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: registry
spec:
  replicas: 2
  template:
    metadata:
      labels:
        name: registry
    spec:
      containers:
      - name: registry
        image: eu.gcr.io/itonk-168412/registry:v3
        ports:
        - containerPort: 80
        env:
        - name: dbhost
          value: "35.187.53.157"
        - name: dbuser
          value: "doe"
        - name: dbpassword
          value: "1234"
        - name: dbdatabase
          value: "registry"
