apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: registry
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: registry
    spec:
      containers:
      - name: registry
        image: eu.gcr.io/itonk-168412/registry:v1
        ports:
        - containerPort: 80
        env:
          - name: "ConnectionStrings:ShareDatabase"
            value: "Server=itonk-db;User Id=root;Password=1234;Database=registry"