apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: requester
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: requester
    spec:
      containers:
      - name: requester
        image: eu.gcr.io/itonk-168412/requester
        ports:
        - containerPort: 80
        env:
          - name: BrokerApiAddress
            value: "http://broker/"
